GET http://localhost:8080/api/v1/turmas
Content-Type: application/json


###
POST http://localhost:8080/api/v1/turmas
Content-Type: application/json

{	
		"sigla": "POO",
		"nome": "Pogramacao orietado a objetos",
		"ano": "2024",
		"vagasMin": 2,
		"vagasMax": 50,
		"semestre": 1
	}


###
POST http://localhost:8080/api/v1/alunos
Content-Type: application/json

{  
  "nome": "Luiz Sebastiao",
  "cpf": "98765422197"  
}

###
GET http://localhost:8080/api/v1/alunos
Content-Type: application/json


###
POST http://localhost:8080/api/v1/turmas/POO-2024-1/matriculas
Content-Type: application/json

{	
  "alunoId": 1
}


###

GET http://localhost:8080/api/v1/turmas/POO-2023-1/matriculas
Content-Type: application/json


###

###

GET http://localhost:8080/api/v1/alunos/1/matriculas
Content-Type: application/json


###